### ISSUE TITLE
Tracer 1.6 has option for categorical data but still won't load non-numerical trace files

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#10]
_From @msuchard on August 13, 2015 23:45_

Originally reported on Google Code with ID 753

```
For example, the attached.
```

Reported by `mdhall272` on 2014-12-09 17:26:05

<hr>
- _Attachment: [wcc_X_9_fixedP_5.net.txt](https://storage.googleapis.com/google-code-attachments/beast-mcmc/issue-753/comment-0/wcc_X_9_fixedP_5.net.txt)_

_Copied from original issue: beast-dev/beast-mcmc#760_

**Comment by walterxie** [comment]
@rambaut @msuchard @alexeid 
Before I recover this useful function, can you please confirm two data types (discrete + continuous) would be enough for Tracer?

It seems we do not need "ordinal" which is discrete and "binary" which is continuous. But we need to implement new statistical functions for java "String" type to calculate mean, variance, ...

Walter

**Comment by walterxie** [comment]
@rambaut @msuchard @alexeid

I fixed this bug, but could not access beast-mcmc. Hi, Andrew and Marc, can you please add me in beast-mcmc project. It is painful to keep doing pull request everytime when I fix a bug.

I am not sure what statistics we should display for non-numeric. Mode? Any advice?

Cheers,
Walter 

![screen shot 2017-03-02 at 3 28 52 pm](https://cloud.githubusercontent.com/assets/5743014/23490834/988b9522-ff5f-11e6-921b-16a4f44e3229.png)

**Comment by rambaut** [comment]
Ordinal is what was previously called 'integer'. Categorical is discrete but has no natural ordering.

**Comment by rambaut** [comment]
Re: statistics for categorical - yes, mode would be sensible. And the frequency of the mode.

**Comment by rambaut** [comment]
Re: binary - I can imagine a situation where we want some explicit analyses of binary data or want to use it as an indicator - without further definition. I think it should be for categorical/ordinal data where values are 0,1 (but we should be able to parse false,true). However, for now we could leave it unimplemented.
