### ISSUE TITLE
Tracer reports increasing ESS values for constant parameter

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/tracer#100]
E.g. for the branch rates normalizing constant, when millions of values have been collected (and each value is the same constant), the ESS value increases proportional with the number of samples. Suggest to just report a dash for the ESS value when the parameter is a constant.

**Comment by GuyBaele** [comment]
Example trace to illustrate my point: ESS=7 (but I've seen it go higher) to a constant value. 

![constantvaluetrace](https://user-images.githubusercontent.com/1092968/30801478-b5d94e86-a1e3-11e7-9b56-8169669ecdf9.png)

**Comment by rambaut** [comment]
Probably we should detect unvarying traces and not show statistics that are not relevant.

**Comment by rambaut** [comment]
This constant value displays correctly:
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/686405/38767459-62e5721a-3fd9-11e8-83a3-ac29d905978d.png">
ESS = 1, variance 0 etc.

**Comment by maxbiostat** [comment]
![image](https://user-images.githubusercontent.com/2875083/38767524-2a8a7580-3fdb-11e8-93c9-9cc590d5d3f1.png)
![image](https://user-images.githubusercontent.com/2875083/38767550-68a141fa-3fdb-11e8-88bb-5ebfead999fc.png)

Latest build: can confirm the weirdness happens when the parameter is different from zero. When `branchRates` is `0.0`, it doesn't seem to be an issue.

**Comment by GuyBaele** [comment]
Example of empirical (i.e. non-estimated) base frequencies:
![screen shot 2018-04-14 at 13 34 30](https://user-images.githubusercontent.com/1092968/38767807-a653e996-3fe8-11e8-8f44-a6fcb405099d.png)

**Comment by walterxie** [comment]
This is caused by "Java double precision sum trouble" https://stackoverflow.com/questions/10786587/java-double-precision-sum-trouble in `DiscreteStatistics`. The mean of `0.2*9001` is `1800.2000000002722` using `double`, which should be `1800.2`

**Comment by walterxie** [comment]
If I change `DiscreteStatistics .mean` to the following code, I have the correct statistics. But this class seems to be used by BEAST as well.
@rambaut Can you please make the decision?

```java
    public static double mean(double[] x) {
        BigDecimal sum = BigDecimal.ZERO;
        int count = x.length;
        for(double aX : x) {
            if( Double.isNaN(aX) ) {
                count--;
            } else {
                sum = sum.add(new BigDecimal(aX, MathContext.DECIMAL64));
            }
        }
        double m = sum.doubleValue();

        return m / (double) count;
    }

```

<img width="1312" alt="screen shot 2018-06-14 at 4 27 42 pm" src="https://user-images.githubusercontent.com/5743014/41391687-374f0e9e-6ff0-11e8-86c6-6819d3e02e05.png">

**Comment by rambaut** [comment]
BigDecimal is orders of magnitude slower than native floating point arithmetic. Best to avoid if possible.

**Comment by rambaut** [comment]
Maybe when the trace is loaded, it could be flagged as being constant and then these could be treated as special cases (i.e., under 'ESS' it could say 'constant').

**Comment by rambaut** [comment]
Perhaps put a '*' in the type column and then at the bottom have "* constant".

**Comment by rambaut** [comment]
Implemented as above.
