### ISSUE TITLE
refreshTraceList() in TracerFrame is called twice when clicking the reload button

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/tracer#103]
seems like this would make it harder to maintain the current selection of traces and statistics when the Reload button is clicked ...

**Comment by rambaut** [comment]
This is usually because there is a StateChangedListener (which is fired twice) rather than an ActionListener which is fired once.

**Comment by rambaut** [comment]
The button was given an Action in its constructor but also an ActionListener.
