### ISSUE TITLE
new version of tracer for Mac

### ISSUE THREAD

**Issue by antoine4ucsd** [beast-dev/tracer#106]
Is the latest version running on Mac?
I am having problem launching trace.jar on my Mac
thanks in advance!

a

**Comment by rambaut** [comment]
trace.jar is not the Tracer program. Downloads are available here https://github.com/beast-dev/tracer/releases

**Comment by antoine4ucsd** [comment]
got it!
Philippe sent me the latest version

thanks 
a





Antoine Chaillon M.D., Ph.D.
Center For Aids Research (CFAR)
Division of Infectious Diseases,
UCSD & VA San Diego Healthcare System 
Stein Clinical Research Building #325
University of California San Diego 
9500 Gilman Drive
La Jolla CA, 92093-0679
(+33) 76-996-8141
