### ISSUE TITLE
Tracer not rescaling trace plot for multiple traces

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#11]
_From @msuchard on August 13, 2015 23:44_

Originally reported on Google Code with ID 717

```
When the posterior of two or more analyses are compared, value of only one analysis
is shown (if the values are very different; e.g. -4000, -6000 and -8000).

```

Reported by `rambaut` on 2013-12-14 08:32:50

<hr>
- _Attachment: 截图3.png<br>![截图3.png](https://storage.googleapis.com/google-code-attachments/beast-mcmc/issue-717/comment-0/截图3.png)_

_Copied from original issue: beast-dev/beast-mcmc#724_

**Comment by rambaut** [comment]
_From @msuchard on August 13, 2015 23:44_

Reported by `rambaut` on 2015-03-05 09:40:39
- **Labels added**: Milestone-Release1.7
- **Labels removed**: Milestone-Release1.6.1

**Comment by walterxie** [comment]
solved but not looking great, if the values are too different.
![screen shot 2017-03-09 at 4 29 40 pm](https://cloud.githubusercontent.com/assets/5743014/23734711/da2e6046-04e5-11e7-931f-e7a3fa819243.png)
