### ISSUE TITLE
Continous density has negative axis

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#111]
For continuous parameters bounded at zero, still shows negative part of axis. 

![tmp](https://user-images.githubusercontent.com/686405/33135954-da5344a2-cf9b-11e7-84b3-6860709ddf4f.png)

**Comment by walterxie** [comment]
The issue is caused by `KDENumericalDensityPlot` to create a negative value in x close to 0 for some plots. Now I add a code to check if `x < lowerBoundary` but raw values are all positive (this will ignore likelihoods), then `xData.add(lowerBoundary);`, otherwise it will use the previous code.
