### ISSUE TITLE
Joint marginal of Integer versus Real does not sort Integer labels

### ISSUE THREAD

**Issue by bredelings** [beast-dev/tracer#112]
If I select I1.RS07.logLambda (R) and #indels1 (I), the #indels labels on the x-axis are in a random order.
If I additionally select I1.RS07.meanIndelLengthMinus1 (R), then it switches to a 3x3 plot of correlation elipses, where it treats the #indels1 as an ordered parameter (or casts it to real) and we see the correlation.
[C1.log](https://github.com/beast-dev/tracer/files/1496730/C1.log)
[C2.log](https://github.com/beast-dev/tracer/files/1496731/C2.log)

No rush of course - I hope its useful.

**Comment by rambaut** [comment]
Joint marginals involving discrete variables aren't working at the moment (after a big code clean up).

**Comment by rambaut** [comment]
I think this is fixed now. Please check.

**Comment by rambaut** [comment]
Will assume fixed and close.
