### ISSUE TITLE
Can't find IntegerViolinPlot

### ISSUE THREAD

**Issue by bredelings** [beast-dev/tracer#115]
Hey, I tried to compile the most recent changes, and I get:

    [javac] /home/bredelings/Devel/tracer/src/tracer/traces/IntervalsPanel.java:259: error: cannot find symbol
    [javac]                             IntegerViolinPlot violinPlot = new IntegerViolinPlot(true, 0.6, lower, upper, false, trace.getFrequencyCounter());
    [javac]                             ^
    [javac]   symbol:   class IntegerViolinPlot
    [javac]   location: class IntervalsPanel
    [javac] /home/bredelings/Devel/tracer/src/tracer/traces/IntervalsPanel.java:259: error: cannot find symbol
    [javac]                             IntegerViolinPlot violinPlot = new IntegerViolinPlot(true, 0.6, lower, upper, false, trace.getFrequencyCounter());
    [javac]                                                                ^
    [javac]   symbol:   class IntegerViolinPlot
    [javac]   location: class IntervalsPanel
    [javac] /home/bredelings/Devel/tracer/src/tracer/traces/SummaryStatisticsPanel.java:329: error: cannot find symbol
    [javac]                             return tc.valueToString(tc.getMode());
    [javac]                                      ^
    [javac]   symbol:   method valueToString(int)
    [javac]   location: variable tc of type TraceCorrelation

**Comment by rambaut** [comment]
Some classes come from the BEAST code. These are packaged into a jar called 'trace.jar' which is in /lib. In this case the jar had not been updated from the BEAST codebase. Fixed now.

**Comment by bredelings** [comment]
I guessed it would be something like that, though I didn't realize BEAST was the source.  Thanks for the jar.
