### ISSUE TITLE
[enhancement] Integer violin plots should space out labels

### ISSUE THREAD

**Issue by bredelings** [beast-dev/tracer#117]
Hi, thanks for the new update.

If you select two statistics, the "Estimates" panel shows violin plots - nice!

However, the y axis labels seem to show a label for every integer, and so if the range exceeds about 40, the y-labels over-write each other.

**Comment by bredelings** [comment]
Additionally, sometimes this happens for real statistics.
1. First select two real statistics - the box plot y-labels are spaced out.
(e.g. I used prior and prior_A1 from the log files I sent before.)
2. Second select two integer statistics - the box y-labels overlap
(I used #indels1 and |indels1|)
3. Third select the original two real statistics - the box plot y-labels are no longer spaced out.

**Comment by rambaut** [comment]
Generally the issue with the labels overlapping automatically is difficult to deal with because it will involve detecting the overlap when drawing and then resizing the labels or omitting some. We can probably guess that if there are > N integers then start to drop labels. I could also add in a control for changing the font size.

**Comment by bredelings** [comment]
Yeah, hmm, I see why that's difficult, and detecting overlaps does seem more complex, partly because it changes when you resize the window.  I think that sometimes having labels every 5 or 10 tick marks can actually be easier to read than having a label at every tick mark. I feel like about N=40 labels would be readable for most plot sizes, but maybe (a) draw a label for each integer if #values < 20 and (b) draw a label for every 5th tick mark if #values > 20 (c) draw a tick mark on round numbers, and have a max of 100 tick marks per axis?  This seems complicated to tune though.

Whatever you are doing with the y-axis labels for continuous variables seems to work fairly well - maybe this would apply to integers if there are a lot of values?  There must be some logic to decide when to use tick marks and when to draw labels.  If that corresponds to a specific value of N, a max number of tick marks, and a number of tick marks per label, then maybe use that value if there are too many integers?  Because sometimes I would be dealing with integers with a range of > 1000.

On the x-axis, it might make sense to control N*(max #digits in label).  But if you use sparser labels, and more tick marks, then this might not be an issue.  Maybe its fine to treat integers with more than 10 digits as a corner case anway.

Anyway, I hope this is helpful.

**Comment by rambaut** [comment]
Marking this as closed. Changing the font size is logged as a separate issue.
