### ISSUE TITLE
Joint Marginal for Integer + Real has overlapping labels on X axis.

### ISSUE THREAD

**Issue by bredelings** [beast-dev/tracer#120]
Hey, I like the new plots for showing integers+reals!  However, sometimes the labels overlap on the x axis.  Also, it looks like sometimes the ranges for some of the x-values extend above the window.
![tracer-window](https://user-images.githubusercontent.com/140268/33281176-53a0dd36-d372-11e7-9c5e-c0f75b9ca7e9.png)

**Comment by rambaut** [comment]
Fixed by automatically leaving labels out if there are > 20 of them. Still doesn't stop overlapping labels if squished up like the graphic above but should help.
