### ISSUE TITLE
Long parameter names in joint marginal panel

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/tracer#124]
When parameters have long names, refreshing the joint marginal panel sometimes leaves parts of those names visible, after a different selection of traces has been made.
1. Select a number (>5) of parameters in the joint marginal panel
2. Go to trace panel and go back to joint marginal panel
3. Select a smaller (<5) number of parameters
4. Short bits of the original parameter names are left on the panel

**Comment by walterxie** [comment]
@GuyBaele I cannot reproduce this in the current dev version.
