### ISSUE TITLE
Colours for trace file, trace file and trace not working

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#129]
Each trace is assigned a colour by the order in the table so it remains consistent as different traces are selected. However, if multiple trace files are loaded, then these colours do not respect the 'by trace file' and 'trace and trace file' options.

**Comment by rambaut** [comment]
Example:

<img width="1312" alt="untitled 3" src="https://user-images.githubusercontent.com/686405/34176948-bbf595dc-e4f9-11e7-9623-bc2cf9120948.png">

**Comment by rambaut** [comment]
This is due to the colours being keyed by the name of the file and the two files being named the same but in different directories (or the same file loaded twice). One possible solution is to include the full path and key from that. It would be preferable to only show the file name but show the full path in a tooltip.

**Comment by walterxie** [comment]
<img width="1312" alt="screen shot 2018-01-31 at 4 26 08 pm" src="https://user-images.githubusercontent.com/5743014/35603721-80f5657c-06a3-11e8-84cd-e6b54a435303.png">
