### ISSUE TITLE
Tracer does not update y-axis properly for multiple traces

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#13]
_From @msuchard on August 13, 2015 23:40_

Originally reported on Google Code with ID 566

```
1. Open Tracer and import a trace file.
2. Select multiple statistics in the left-hand column.
3. The y-axis of the Trace display does not update properly with the minimum and maximum
of the entire set of the selected traces.  Instead, minimum and maximum derive from
the last selected trace.
```

Reported by `trevor@bedford.io` on 2011-12-15 14:42:14

_Copied from original issue: beast-dev/beast-mcmc#574_

**Comment by rambaut** [comment]
_From @msuchard on August 13, 2015 23:40_

Reported by `trevor@bedford.io` on 2011-12-15 14:43:49
- **Labels added**: tracer

**Comment by rambaut** [comment]
_From @msuchard on August 13, 2015 23:40_

Reported by `rambaut` on 2012-03-04 10:12:58
- **Labels added**: Tracer, Milestone-Release1.6
- **Labels removed**: tracer

**Comment by walterxie** [comment]
Duplicate to Tracer not rescaling trace plot for multiple traces #11
