### ISSUE TITLE
Not possible to visualize >1 variable.

### ISSUE THREAD

**Issue by bredelings** [beast-dev/tracer#131]
With just one trace file loaded, if I select two variables then
1. The Estimates tab shows numerical statistics of both, but below is the phrase "No traces selected" instead of a plot.
2. The Marginal Density tab shows the density of the first variable.
3. The Joint Marginal shows 'Select two traces to visualize the joint density'
4. The Trace tab shows the trace for the first variable.

**Comment by rambaut** [comment]
I can't replicate this on the HEAD version. Perhaps it has been fixed?

**Comment by bredelings** [comment]
Hmmm... seems like its fixed.
