### ISSUE TITLE
ViolinPlot cannot handle trace having less than 3 values

### ISSUE THREAD

**Issue by walterxie** [beast-dev/tracer#133]
@rambaut 
ViolinPlot cannot handle trace having less than 3 values, which mostly happens for non-real type, such as host.indicators in the example log (only has 0, 1).

To replicate, load batRABV.log, and select any 2 host.indicators together, then get a strange triangle. But ViolinPlot works for 3 and more than 3 values.

<img width="700" alt="screen shot 2018-01-30 at 3 33 51 pm" src="https://user-images.githubusercontent.com/5743014/35545243-07bc975a-05d3-11e8-9391-60842907199c.png">

**Comment by walterxie** [comment]
change to interval plot for value < 3?

**Comment by walterxie** [comment]
@rambaut 
I updated IntervalsPanel.setupTraces() after line 197 for discrete trace. ViolinPlot works fine when there are more than 2 values in the trace. But when <= 2, hpd lower and upper will not be calculated properly, and then ViolinPlot will make a funny plot. To solve this problem, I use the min and max for 2 values or the mean for 1 value, and also change to IntegerViolinPlot. It looks good now.  

<img width="1312" alt="screen shot 2018-01-31 at 12 19 13 pm" src="https://user-images.githubusercontent.com/5743014/35599182-6a4c5432-068c-11e8-983f-7e7e86db04b0.png">

**Comment by rambaut** [comment]
Interesting. Not the most obvious visualization for binary traces but will do for now. Possibly better to use stacked bars?
