### ISSUE TITLE
Integer joint marginal filled boxes are too large?

### ISSUE THREAD

**Issue by bredelings** [beast-dev/tracer#143]
Integer joint marginal filled boxes are too large.  Perhaps this is intended?  It certainly looked different before.
![screenshot from 2018-01-31 11-05-39](https://user-images.githubusercontent.com/140268/35634288-534911a2-0679-11e8-9887-3b8088c1bc7e.png)
![screenshot from 2018-01-28 21-13-00](https://user-images.githubusercontent.com/140268/35634296-58f84f3c-0679-11e8-8d19-7b6bb65c926c.png)

This should be from current HEAD with a clean build.

**Comment by rambaut** [comment]
Looks pretty cool though?

**Comment by rambaut** [comment]
The issue is the axis dropping some of the labels, I think. The boxes are defined by the label spacing not the tick marks.

**Comment by bredelings** [comment]
Ha ha, it does look cool.  The figures are a bit...busy ... though :-P

Yeah, I see, that the widths are same same as the intervals between tick marks.  I suppose if you binned all the individual cells, in the [tick width]x[tick width] square, then this would avoid drawing overlapping dots.

But at that point, I think the benefit of distinguishing individual values is lost, and it might be worth automatically promoting the discrete values to continuous values for the purpose of the plot.  Thus, there's probably some value in fixing this by not merging different cells.

it does raise the general question of automatically promoting integer values to continuous for certain plots, though.

**Comment by rambaut** [comment]
You should just be able to select the trace and switch it to 'Real' type. Integers should then be treated as continuous.

**Comment by rambaut** [comment]
Tiles are now sized as the 'minor ticks'.
