### ISSUE TITLE
Should the Integer trace type be auto-detected?

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/tracer#144]
Currently, I only see R(eal) and C(ategorical) trace types being auto-detected, but not the I(nteger) trace type, such as for host.nonZeroRates or state.nonZeroRates for example. Should this be the case (they are currently detected as Real)?

**Comment by rambaut** [comment]
host.nonZeroRates or state.nonZeroRates are autodetected as integer for me.

<img width="336" alt="untitled 3" src="https://user-images.githubusercontent.com/686405/35642299-9fbcc57e-06ba-11e8-972c-7e4415909bf7.png">

**Comment by GuyBaele** [comment]
strange, double-checked that I was using the latest checkout from repo ...

<img width="362" alt="screen shot 2018-01-31 at 20 14 21" src="https://user-images.githubusercontent.com/1092968/35642439-68833648-06c3-11e8-8d55-d0135f0f2f5f.png">

**Comment by rambaut** [comment]
Presumably there is something specific to the file you are using.

**Comment by walterxie** [comment]
@GuyBaele 
I think your data may contain decimal for integer, such as 0.0, 1.0, etc., which will be treated as real type in Tracer. Please have a look the example log. They are all looking like 0, 1, 2 , ...
