### ISSUE TITLE
Seleting multiple traces for visualization

### ISSUE THREAD

**Issue by santiagosnchez** [beast-dev/tracer#147]
In previous versions of Tracer, one was able to select multiple traces for visualization. I even remember that the test release of version 1.7 was able to generate boxplots in the estimates tab. I trying out the this release version: [0863494](https://github.com/beast-dev/tracer/commit/08634942c34eaa146f681f85becede0d0240d2c4) and it only shows one trace when multiple are selected. This is a problem too for joint distributions.

Thanks,
Santiago

![screen2](https://user-images.githubusercontent.com/22626974/40446982-175c32ae-5e9f-11e8-9b3a-dfb764ffaeda.png)
![screen1](https://user-images.githubusercontent.com/22626974/40446983-1769ae52-5e9f-11e8-847e-668402c291ab.png)

**Comment by rambaut** [comment]
This was an issue with the packaging of the Mac version. It is now fixed an a new DMG uploaded (because no code has changed, I have not changed the version number). Just re-download and overwrite the old binary.
