### ISSUE TITLE
cannot select multiple parameters in 1.7

### ISSUE THREAD

**Issue by wbsimey** [beast-dev/tracer#148]
Looking at a BEAST2.5 log file for a relaxed clock FBD analysis in Tracer 1.7, I am unable to view multiple parameters as I can in v1.6. 
I have attached screenshot of same log files in v1.6 and v1.7

on Win10 64-bit, Java 10.
![screenshot 2018-06-12 11 11 18](https://user-images.githubusercontent.com/2200085/41308687-7ea7e038-6e31-11e8-9a66-77f68f7195e8.png)
![screenshot 2018-06-12 11 10 44](https://user-images.githubusercontent.com/2200085/41308690-7ebd29de-6e31-11e8-9049-ed8510173e59.png)

**Comment by walterxie** [comment]
Can you upload your log file please? I cannot replicate using both log files having relaxed clock https://taming-the-beast.org/tutorials/species-tree-clocks/ and FDB https://taming-the-beast.org/tutorials/FBD-tutorial/.

<img width="1312" alt="screen shot 2018-06-13 at 3 14 12 pm" src="https://user-images.githubusercontent.com/5743014/41328571-d38c8086-6f1c-11e8-9a42-89b6e9b4061e.png">

<img width="1312" alt="screen shot 2018-06-13 at 3 14 12 pm" src="https://user-images.githubusercontent.com/5743014/41328581-dd1601d6-6f1c-11e8-8904-33e5a92c7285.png">

**Comment by GuyBaele** [comment]
This was indeed an issue when we first released the Tracer 1.7 files. Can you please try downloading Tracer 1.7 again to check if this is still an issue?

**Comment by wbsimey** [comment]
I downloaded Tracer1.7 again from https://github.com/beast-dev/tracer/releases/tag/v1.7. and I see the same behavior for all BEAST2 log files; I cannot visualize multiple traces simultaneously, but in v1.6 I can.

**Comment by drelo** [comment]
Sorry to post here but I didn't want to duplicate a question, I am having the same issue

I just downloaded the newest Tracer

I currently have 
```
java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
Ubuntu 16.04
```
I attached the log file.
I just opened those 2 traces with Tracer 1.6 and it worked fine.

Thanks for your help

[tracer17.log](https://github.com/beast-dev/tracer/files/2099592/tracer17.log)

**Comment by walterxie** [comment]
@drelo @wbsimey 
Thank you to report the bug. I just double-checked again by actually running primate-mtDNA XML in BEAST 2.5.0 and loaded the log to Tracer 1.7. I still could not replicate the issue in the Mac version, but I successfully replicated it when I ran the Linux version in Mac. I did not find a PC here, but I suspected it would be the same error in Windows version.

We are working to solve this at the moment.

**Comment by walterxie** [comment]
I do not think the current Java code was causing this issue after my investigation. This issue can be replicated by `tracer.jar` only in the previous released Linux version. I tested the Linux release by myself using the latest development version, it was working well. 
 
I presume the Linux version and Windows version might be interrupted during the release process, so that a new release would solve this problem (if assuming the Windows version has the same problem with Linux version).

**Comment by wbsimey** [comment]
I downloaded Tracer 1.7.1 for Windows and Linux (Ubuntu 16.04) and the issue has been resolved for both platforms. thank you.
