### ISSUE TITLE
Tracer ESS significant digits

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#15]
_From @msuchard on August 13, 2015 23:35_

Originally reported on Google Code with ID 376

```
Do we *really* need 3 significant digits in Tracer ESS? 
```

Reported by `jheled` on 2010-08-25 08:48:56

_Copied from original issue: beast-dev/beast-mcmc#386_

**Comment by rambaut** [comment]
_From @msuchard on August 13, 2015 23:35_

Reported by `rambaut` on 2010-09-10 12:29:14
- **Labels added**: Tracer, 1.5

**Comment by walterxie** [comment]
it is 4 now.

**Comment by rambaut** [comment]
I suspect Marc was suggesting fewer decimal places.

**Comment by rambaut** [comment]
For ESSs it now uses 1 dp
