### ISSUE TITLE
The legend does not show file names

### ISSUE THREAD

**Issue by maxbiostat** [beast-dev/tracer#151]
If you check out the latest version, open multiple files and try to visualise them all, you don't get file names in the legend:
![image](https://user-images.githubusercontent.com/2875083/58831841-fbeb7400-8623-11e9-85d9-4a70b77cefab.png)

**Comment by rambaut** [comment]
Shows file names (less the .log extension) if two or more files are selected and trace names if two or more traces are selected (otherwise just one or the other).
