### ISSUE TITLE
[README] Installation requirements?

### ISSUE THREAD

**Issue by rubyFeedback** [beast-dev/tracer#169]
Hey folks,

For a university course we have to use tracer.

I haven't checked it yet but I assume java is necessary. Perhaps anything else too?

It would be helpful to briefly mention the requirements - does not need to be detailed,
just a quick, rough overview (for instance "ant" was mentioned too I think but I 
don't know if we have to install it as well). Thanks  for considering!

**Comment by walterxie** [comment]
It is mentioned in the tutorial [how to use Tracer to analyse the output from BEAST](https://beast.community/analysing_beast_output). Please read the documentation.
