### ISSUE TITLE
Problem ebsp.log running Coalescent Extended Bayesian Skyline

### ISSUE THREAD

**Issue by arenvale** [beast-dev/tracer#173]
Hi Walter!
I have performed a run in Beast2 with a Coalescent Extended Bayesian Skyline model. I have opened the ebsp.log (the file used to plot the demographic history posterior) with Tracer but I get what is observed in the figure.
![EBSP_Tracer](https://user-images.githubusercontent.com/72875846/163858543-3e776399-b2dd-4ad8-be1a-c76871a60c54.png)
The .log file generated in the run looks fine.
I don't know if this is normal or I should modify the parameters of the run to be able to observe the convergence of the parameters in this file.
I'm using Windows 10.
If you could help me I would appreciate it.
Regards,
Valeria

**Comment by walterxie** [comment]
I think you picked up the wrong log file. There are normally 2 log files, one is to log the parameter states of MCMC, which is named as "mystery.log" in the tutorial XML `<logger id="tracelog" fileName="mystery.log" logEvery="100000" model="@posterior" ...`. It is the log file for Tracer. But the "EBSP.log" from `<logger id="EBSPLogger" fileName="EBSP.log" ...` is a developer customized format, which cannot be loaded properly to Tracer.

**Comment by arenvale** [comment]
Ok, great! I already opened the file similar to the "mystery.log" and it seems to have been a good run, but I thought I also had to check the ebsp.log file. 
Thank you very much!
