### ISSUE TITLE
Issue running on Windows

### ISSUE THREAD

**Issue by jb16159** [beast-dev/tracer#177]
Hi Tracer Developers,

I'm having trouble opening Tracer on my Windows 11 Enterprise PC. When I load the application, an error message states "Could not find main class: tracer.application.TracerApp". Do you have any idea what might be causing this or how it can be fixed?  I really value viewing the entire MCMC traces in tracer and have used them many times before on Windows 10 PCs. I have also downloaded Java 6 (but have both this and the latest JRE on my operating system). Before downloading Java 6, it was stating a different error message, so I don't think this is the problem. Any ideas would be gratefully appreciated!

Best wishes,
Jo

**Comment by rambaut** [comment]
This is likely to be a problem specific to a particular JVM/Windows combination. Closing for now without more details of how to replicate it. Tracer now compiles to minimum of Java 8 so a Java 6 JVM will not work.
