### ISSUE TITLE
Tracer hangs on very low variance traces

### ISSUE THREAD

**Issue by rbouckaert** [beast-dev/tracer#179]
Trying to load a trace file with the content like below will make tracer hang and leave it unresponsive.

Sample	parameter
0	1.0896463746291896
5000	1.0896463746291898
10000	1.08964637462919
15000	1.0896463746291902
20000	1.0896463746291898
25000	1.08964637462919
30000	1.0896463746291896
35000	1.0896463746291896
40000	1.08964637462919
45000	1.0896463746291893
50000	1.08964637462919
55000	1.0896463746291902
60000	1.08964637462919
65000	1.0896463746291898
70000	1.08964637462919
75000	1.0896463746291905
80000	1.0896463746291902
85000	1.0896463746291902
90000	1.0896463746291905
95000	1.0896463746291898
100000	1.0896463746291898
105000	1.08964637462919
110000	1.08964637462919
115000	1.0896463746291893
120000	1.0896463746291896
125000	1.0896463746291896
130000	1.0896463746291902
135000	1.0896463746291898
140000	1.08964637462919
145000	1.0896463746291896
150000	1.0896463746291902
155000	1.0896463746291896
160000	1.0896463746291898
165000	1.0896463746291898
170000	1.08964637462919
175000	1.0896463746291902
180000	1.0896463746291905
185000	1.0896463746291902
190000	1.0896463746291902
195000	1.0896463746291902
200000	1.0896463746291896
205000	1.08964637462919
210000	1.08964637462919
215000	1.0896463746291902
220000	1.0896463746291898
225000	1.0896463746291896
230000	1.0896463746291898
235000	1.0896463746291898
240000	1.0896463746291902
245000	1.08964637462919
250000	1.0896463746291902
255000	1.0896463746291896
260000	1.08964637462919
265000	1.0896463746291905
270000	1.0896463746291905
275000	1.0896463746291907
280000	1.08964637462919
285000	1.08964637462919
290000	1.0896463746291896
295000	1.0896463746291902
300000	1.0896463746291896
305000	1.0896463746291896
310000	1.0896463746291902
315000	1.0896463746291896
320000	1.08964637462919
325000	1.08964637462919
330000	1.0896463746291905
335000	1.0896463746291902
340000	1.0896463746291896
345000	1.08964637462919
350000	1.0896463746291902
355000	1.0896463746291905
360000	1.0896463746291902
365000	1.0896463746291898
370000	1.08964637462919
375000	1.08964637462919
380000	1.0896463746291902
385000	1.0896463746291898
390000	1.0896463746291902
395000	1.0896463746291896
400000	1.0896463746291902
405000	1.0896463746291898
410000	1.0896463746291898
415000	1.0896463746291898
420000	1.0896463746291902
425000	1.0896463746291898
430000	1.08964637462919
435000	1.0896463746291902
440000	1.0896463746291896
445000	1.08964637462919
450000	1.08964637462919
455000	1.0896463746291905
460000	1.0896463746291896
465000	1.0896463746291898
470000	1.0896463746291905
475000	1.0896463746291898
480000	1.0896463746291905
485000	1.08964637462919
490000	1.0896463746291902
495000	1.08964637462919
500000	1.0896463746291898
505000	1.0896463746291898
510000	1.0896463746291902
515000	1.0896463746291902
520000	1.0896463746291902
525000	1.0896463746291896
530000	1.08964637462919
535000	1.08964637462919
540000	1.0896463746291896
545000	1.08964637462919
550000	1.08964637462919
555000	1.08964637462919
560000	1.0896463746291902
565000	1.08964637462919
570000	1.08964637462919
575000	1.0896463746291898
580000	1.08964637462919
585000	1.0896463746291898
590000	1.08964637462919
595000	1.08964637462919
600000	1.0896463746291905
605000	1.08964637462919
610000	1.0896463746291898
615000	1.0896463746291907
620000	1.08964637462919
625000	1.0896463746291896
630000	1.0896463746291898
635000	1.0896463746291902
640000	1.0896463746291896
645000	1.08964637462919
650000	1.08964637462919
655000	1.0896463746291898
660000	1.08964637462919
665000	1.0896463746291902
670000	1.0896463746291902
675000	1.08964637462919
680000	1.0896463746291896
685000	1.0896463746291893
690000	1.08964637462919
695000	1.08964637462919
700000	1.08964637462919
705000	1.0896463746291902
710000	1.08964637462919
715000	1.08964637462919
720000	1.0896463746291898
725000	1.08964637462919
730000	1.0896463746291896
735000	1.08964637462919
740000	1.0896463746291893
745000	1.0896463746291891
750000	1.0896463746291898
755000	1.0896463746291902
760000	1.0896463746291902
765000	1.0896463746291902
770000	1.08964637462919
775000	1.0896463746291898
780000	1.0896463746291893
785000	1.0896463746291898
790000	1.0896463746291905
795000	1.0896463746291896
800000	1.08964637462919
805000	1.08964637462919
810000	1.08964637462919
815000	1.08964637462919
820000	1.0896463746291898
825000	1.0896463746291896
830000	1.0896463746291898
835000	1.08964637462919
840000	1.0896463746291902
845000	1.0896463746291898
850000	1.0896463746291902
855000	1.0896463746291905
860000	1.08964637462919
865000	1.0896463746291898
870000	1.0896463746291902
875000	1.08964637462919
880000	1.0896463746291896
885000	1.0896463746291902
890000	1.0896463746291902
895000	1.0896463746291898
900000	1.08964637462919
905000	1.0896463746291896
910000	1.0896463746291893
915000	1.08964637462919
920000	1.0896463746291893
925000	1.08964637462919
930000	1.08964637462919
935000	1.0896463746291907
940000	1.0896463746291898
945000	1.0896463746291898
950000	1.08964637462919
955000	1.08964637462919
960000	1.0896463746291896
965000	1.0896463746291898
970000	1.0896463746291898
975000	1.0896463746291905
980000	1.08964637462919
985000	1.0896463746291905
990000	1.0896463746291902
995000	1.0896463746291898
1000000	1.0896463746291898
1005000	1.08964637462919
1010000	1.0896463746291893
1015000	1.08964637462919
1020000	1.0896463746291898
1025000	1.08964637462919
1030000	1.0896463746291898
1035000	1.08964637462919
1040000	1.0896463746291902
1045000	1.0896463746291898
1050000	1.0896463746291896
1055000	1.0896463746291898
1060000	1.0896463746291905
1065000	1.0896463746291902
1070000	1.08964637462919
1075000	1.0896463746291902
1080000	1.0896463746291893
1085000	1.0896463746291902
1090000	1.0896463746291902
1095000	1.08964637462919
1100000	1.0896463746291896
1105000	1.08964637462919
1110000	1.0896463746291902
1115000	1.0896463746291898
1120000	1.0896463746291907
1125000	1.08964637462919
1130000	1.08964637462919
1135000	1.0896463746291898
1140000	1.08964637462919
1145000	1.0896463746291905
1150000	1.0896463746291891
1155000	1.08964637462919
1160000	1.0896463746291898
1165000	1.0896463746291896
1170000	1.08964637462919
1175000	1.08964637462919
1180000	1.0896463746291898
1185000	1.0896463746291896
1190000	1.08964637462919
1195000	1.0896463746291905
1200000	1.0896463746291898
1205000	1.0896463746291896
1210000	1.0896463746291893
1215000	1.0896463746291893
1220000	1.0896463746291898
1225000	1.0896463746291898
1230000	1.08964637462919
1235000	1.08964637462919
1240000	1.0896463746291896
1245000	1.08964637462919
1250000	1.0896463746291898
1255000	1.0896463746291898
1260000	1.0896463746291898
1265000	1.08964637462919
1270000	1.0896463746291896
1275000	1.0896463746291905
1280000	1.0896463746291896
1285000	1.08964637462919
1290000	1.0896463746291902
1295000	1.08964637462919
1300000	1.08964637462919
1305000	1.0896463746291898
1310000	1.0896463746291898
1315000	1.08964637462919
1320000	1.0896463746291898
1325000	1.0896463746291896
1330000	1.08964637462919
1335000	1.0896463746291898
1340000	1.08964637462919
1345000	1.0896463746291898
1350000	1.0896463746291902
1355000	1.0896463746291902
1360000	1.0896463746291902
1365000	1.0896463746291905
1370000	1.0896463746291902
1375000	1.08964637462919
1380000	1.0896463746291902
1385000	1.0896463746291896
1390000	1.0896463746291898
1395000	1.0896463746291898
1400000	1.08964637462919
1405000	1.08964637462919
1410000	1.08964637462919
1415000	1.0896463746291896
1420000	1.0896463746291902
1425000	1.0896463746291893
1430000	1.0896463746291902
1435000	1.0896463746291893
1440000	1.0896463746291907
1445000	1.0896463746291905
1450000	1.089646374629191
1455000	1.0896463746291898
1460000	1.0896463746291905
1465000	1.0896463746291905
1470000	1.0896463746291902
1475000	1.0896463746291896
1480000	1.0896463746291905
1485000	1.0896463746291898
1490000	1.0896463746291902
1495000	1.08964637462919
1500000	1.0896463746291898
1505000	1.0896463746291905
1510000	1.0896463746291896
1515000	1.08964637462919
1520000	1.0896463746291898
1525000	1.0896463746291896
1530000	1.0896463746291898
1535000	1.08964637462919
1540000	1.0896463746291898
1545000	1.0896463746291907
1550000	1.08964637462919
1555000	1.0896463746291902
1560000	1.0896463746291898
1565000	1.0896463746291902
1570000	1.08964637462919
1575000	1.0896463746291896
1580000	1.08964637462919
1585000	1.0896463746291902
1590000	1.0896463746291891
1595000	1.08964637462919
1600000	1.0896463746291893
1605000	1.0896463746291898
1610000	1.0896463746291898
1615000	1.0896463746291898
1620000	1.0896463746291896
1625000	1.0896463746291907
1630000	1.0896463746291898
1635000	1.0896463746291902
1640000	1.08964637462919
1645000	1.0896463746291902
1650000	1.0896463746291902
1655000	1.0896463746291898
1660000	1.0896463746291898
1665000	1.0896463746291896
1670000	1.0896463746291893
1675000	1.0896463746291898
1680000	1.0896463746291907
1685000	1.0896463746291898
1690000	1.08964637462919
1695000	1.0896463746291905
1700000	1.0896463746291902
1705000	1.0896463746291896
1710000	1.0896463746291902
1715000	1.0896463746291902
1720000	1.0896463746291898
1725000	1.0896463746291898
1730000	1.0896463746291896
1735000	1.0896463746291898
1740000	1.0896463746291907
1745000	1.0896463746291898
1750000	1.0896463746291898
1755000	1.0896463746291896
1760000	1.0896463746291898
1765000	1.0896463746291905
1770000	1.0896463746291893
1775000	1.0896463746291902
1780000	1.0896463746291902
1785000	1.0896463746291902
1790000	1.0896463746291898
1795000	1.08964637462919
1800000	1.0896463746291898
1805000	1.0896463746291896
1810000	1.0896463746291898
1815000	1.0896463746291896
1820000	1.08964637462919
1825000	1.0896463746291905
1830000	1.08964637462919
1835000	1.0896463746291898
1840000	1.08964637462919
1845000	1.0896463746291893
1850000	1.08964637462919
1855000	1.08964637462919
1860000	1.0896463746291898
1865000	1.0896463746291891
1870000	1.0896463746291898
1875000	1.0896463746291898
1880000	1.08964637462919
1885000	1.08964637462919
1890000	1.08964637462919
1895000	1.0896463746291905
1900000	1.0896463746291896
1905000	1.0896463746291902
1910000	1.0896463746291896
1915000	1.0896463746291898
1920000	1.08964637462919
1925000	1.0896463746291898
1930000	1.0896463746291902
1935000	1.08964637462919
1940000	1.0896463746291902
1945000	1.08964637462919
1950000	1.0896463746291902
1955000	1.0896463746291893
1960000	1.0896463746291893
1965000	1.08964637462919
1970000	1.0896463746291896
1975000	1.0896463746291896
1980000	1.08964637462919
1985000	1.0896463746291902
1990000	1.08964637462919
1995000	1.0896463746291902
2000000	1.0896463746291898
2005000	1.0896463746291905
2010000	1.08964637462919
2015000	1.0896463746291896
2020000	1.0896463746291902
2025000	1.0896463746291898
2030000	1.08964637462919
2035000	1.0896463746291905
2040000	1.0896463746291896
2045000	1.08964637462919
2050000	1.0896463746291898
2055000	1.0896463746291907
2060000	1.0896463746291898
2065000	1.0896463746291896
2070000	1.08964637462919
2075000	1.08964637462919
2080000	1.0896463746291896
2085000	1.0896463746291898
2090000	1.08964637462919
2095000	1.0896463746291898
2100000	1.08964637462919
2105000	1.08964637462919
2110000	1.0896463746291898
2115000	1.0896463746291902
2120000	1.0896463746291902
2125000	1.08964637462919
2130000	1.0896463746291898
2135000	1.0896463746291898
2140000	1.0896463746291898
2145000	1.0896463746291907
2150000	1.0896463746291902
2155000	1.0896463746291898
2160000	1.0896463746291902
2165000	1.08964637462919
2170000	1.0896463746291898
2175000	1.08964637462919
2180000	1.0896463746291898
2185000	1.08964637462919
2190000	1.0896463746291898
2195000	1.0896463746291896
2200000	1.0896463746291902
2205000	1.08964637462919
2210000	1.08964637462919
2215000	1.0896463746291898
2220000	1.08964637462919
2225000	1.0896463746291905
2230000	1.0896463746291896
2235000	1.0896463746291902
2240000	1.0896463746291896
2245000	1.0896463746291902
2250000	1.0896463746291898
2255000	1.0896463746291898
2260000	1.08964637462919
2265000	1.0896463746291902
2270000	1.08964637462919
2275000	1.08964637462919
2280000	1.0896463746291898
2285000	1.08964637462919
2290000	1.0896463746291898
2295000	1.0896463746291902
2300000	1.08964637462919
2305000	1.0896463746291898
2310000	1.0896463746291902
2315000	1.0896463746291898
2320000	1.0896463746291898
2325000	1.08964637462919
2330000	1.0896463746291905
2335000	1.0896463746291898
2340000	1.0896463746291898
2345000	1.0896463746291896
2350000	1.0896463746291893
2355000	1.08964637462919
2360000	1.0896463746291902
2365000	1.08964637462919
2370000	1.0896463746291898
2375000	1.0896463746291896
2380000	1.0896463746291902
2385000	1.0896463746291902
2390000	1.08964637462919
2395000	1.0896463746291902
2400000	1.08964637462919
2405000	1.0896463746291902
2410000	1.0896463746291902
2415000	1.0896463746291898
2420000	1.0896463746291896
2425000	1.08964637462919
2430000	1.08964637462919
2435000	1.0896463746291902
2440000	1.0896463746291902
2445000	1.0896463746291896
2450000	1.08964637462919
2455000	1.0896463746291898
2460000	1.08964637462919
2465000	1.0896463746291902
2470000	1.08964637462919
2475000	1.08964637462919
2480000	1.0896463746291898
2485000	1.0896463746291896
2490000	1.0896463746291898
2495000	1.0896463746291898
2500000	1.0896463746291905
2505000	1.0896463746291896
2510000	1.0896463746291902
2515000	1.0896463746291898
2520000	1.08964637462919
2525000	1.0896463746291898
2530000	1.08964637462919
2535000	1.08964637462919
2540000	1.0896463746291898
2545000	1.0896463746291896
2550000	1.0896463746291902
2555000	1.08964637462919
2560000	1.0896463746291898
2565000	1.08964637462919
2570000	1.0896463746291898
2575000	1.0896463746291898
2580000	1.0896463746291898
2585000	1.0896463746291898
2590000	1.0896463746291902
2595000	1.08964637462919
2600000	1.0896463746291898
2605000	1.08964637462919
2610000	1.0896463746291896
2615000	1.0896463746291896
2620000	1.08964637462919
2625000	1.0896463746291902
2630000	1.0896463746291902
2635000	1.0896463746291902
2640000	1.0896463746291896
2645000	1.0896463746291896
2650000	1.08964637462919
2655000	1.08964637462919
2660000	1.0896463746291898
2665000	1.0896463746291896
2670000	1.0896463746291898
2675000	1.0896463746291896
2680000	1.08964637462919
2685000	1.0896463746291898
2690000	1.0896463746291898
2695000	1.08964637462919
2700000	1.0896463746291902
2705000	1.0896463746291898
2710000	1.0896463746291896
2715000	1.08964637462919
2720000	1.0896463746291898
2725000	1.08964637462919
2730000	1.08964637462919
2735000	1.0896463746291898
2740000	1.0896463746291898
2745000	1.0896463746291902
2750000	1.0896463746291902
2755000	1.08964637462919
2760000	1.0896463746291902
2765000	1.0896463746291902
2770000	1.0896463746291902
2775000	1.08964637462919
2780000	1.08964637462919
2785000	1.08964637462919
2790000	1.0896463746291896
2795000	1.0896463746291893
2800000	1.0896463746291898
2805000	1.0896463746291898
2810000	1.0896463746291893
2815000	1.0896463746291902
2820000	1.0896463746291905
2825000	1.0896463746291902
2830000	1.08964637462919
2835000	1.08964637462919
2840000	1.0896463746291902
2845000	1.0896463746291905
2850000	1.0896463746291902
2855000	1.08964637462919
2860000	1.08964637462919
2865000	1.0896463746291902
2870000	1.08964637462919
2875000	1.0896463746291898
2880000	1.0896463746291902
2885000	1.0896463746291896
2890000	1.08964637462919
2895000	1.0896463746291896
2900000	1.0896463746291905
2905000	1.0896463746291898
2910000	1.08964637462919
2915000	1.0896463746291898
2920000	1.0896463746291898
2925000	1.0896463746291896
2930000	1.0896463746291896
2935000	1.08964637462919
2940000	1.0896463746291898
2945000	1.0896463746291907
2950000	1.0896463746291898
2955000	1.0896463746291898
2960000	1.0896463746291905
2965000	1.08964637462919
2970000	1.08964637462919
2975000	1.08964637462919
2980000	1.0896463746291902
2985000	1.0896463746291902
2990000	1.0896463746291902
2995000	1.0896463746291898
3000000	1.08964637462919
3005000	1.08964637462919
3010000	1.0896463746291896
3015000	1.0896463746291898
3020000	1.0896463746291902
3025000	1.0896463746291896
3030000	1.0896463746291893
3035000	1.08964637462919
3040000	1.0896463746291893
3045000	1.08964637462919
3050000	1.0896463746291898
3055000	1.0896463746291902
3060000	1.0896463746291896
3065000	1.0896463746291893
3070000	1.08964637462919
3075000	1.08964637462919
3080000	1.08964637462919
3085000	1.08964637462919
3090000	1.08964637462919
3095000	1.0896463746291902
3100000	1.08964637462919
3105000	1.08964637462919
3110000	1.0896463746291898
3115000	1.08964637462919
3120000	1.0896463746291893
3125000	1.08964637462919
3130000	1.08964637462919
3135000	1.08964637462919
3140000	1.0896463746291905
3145000	1.0896463746291898
3150000	1.0896463746291898
3155000	1.0896463746291902
3160000	1.0896463746291898
3165000	1.08964637462919
3170000	1.08964637462919
3175000	1.08964637462919
3180000	1.0896463746291902
3185000	1.0896463746291898
3190000	1.0896463746291905
3195000	1.0896463746291898
3200000	1.08964637462919
3205000	1.08964637462919
3210000	1.08964637462919
3215000	1.0896463746291896
3220000	1.0896463746291905
3225000	1.08964637462919
3230000	1.08964637462919
3235000	1.08964637462919
3240000	1.0896463746291898
3245000	1.08964637462919
3250000	1.08964637462919
3255000	1.0896463746291898
3260000	1.0896463746291905
3265000	1.08964637462919
3270000	1.0896463746291896
3275000	1.0896463746291902
3280000	1.0896463746291902
3285000	1.0896463746291898
3290000	1.0896463746291902
3295000	1.08964637462919
3300000	1.0896463746291905
3305000	1.0896463746291898
3310000	1.08964637462919
3315000	1.08964637462919
3320000	1.0896463746291898
3325000	1.08964637462919
3330000	1.0896463746291905
3335000	1.0896463746291898
3340000	1.08964637462919
3345000	1.0896463746291898
3350000	1.0896463746291898
3355000	1.0896463746291896
3360000	1.0896463746291905
3365000	1.0896463746291893
3370000	1.0896463746291898
3375000	1.08964637462919
3380000	1.0896463746291902
3385000	1.0896463746291896
3390000	1.0896463746291905
3395000	1.0896463746291898
3400000	1.0896463746291893
3405000	1.0896463746291898
3410000	1.0896463746291905
3415000	1.0896463746291902
3420000	1.08964637462919
3425000	1.0896463746291902
3430000	1.08964637462919
3435000	1.0896463746291898
3440000	1.08964637462919
3445000	1.0896463746291902
3450000	1.08964637462919
3455000	1.08964637462919
3460000	1.0896463746291896
3465000	1.0896463746291907
3470000	1.08964637462919
3475000	1.0896463746291898
3480000	1.08964637462919
3485000	1.0896463746291902
3490000	1.0896463746291898
3495000	1.0896463746291898
3500000	1.0896463746291898
3505000	1.0896463746291898
3510000	1.0896463746291902
3515000	1.0896463746291896
3520000	1.0896463746291893
3525000	1.0896463746291898
3530000	1.0896463746291898
3535000	1.0896463746291902
3540000	1.08964637462919
3545000	1.0896463746291902
3550000	1.0896463746291898
3555000	1.08964637462919
3560000	1.08964637462919
3565000	1.0896463746291905
3570000	1.0896463746291898
3575000	1.08964637462919
3580000	1.08964637462919
3585000	1.0896463746291907
3590000	1.0896463746291902
3595000	1.0896463746291898
3600000	1.0896463746291898
3605000	1.08964637462919
3610000	1.08964637462919
3615000	1.0896463746291896
3620000	1.08964637462919
3625000	1.0896463746291905
3630000	1.0896463746291896
3635000	1.08964637462919
3640000	1.08964637462919
3645000	1.0896463746291893
3650000	1.0896463746291896
3655000	1.0896463746291898
3660000	1.0896463746291905
3665000	1.0896463746291898
3670000	1.0896463746291905
3675000	1.0896463746291898
3680000	1.0896463746291905
3685000	1.0896463746291898
3690000	1.08964637462919
3695000	1.0896463746291898
3700000	1.08964637462919
3705000	1.0896463746291898
3710000	1.08964637462919
3715000	1.08964637462919
3720000	1.0896463746291905
3725000	1.0896463746291898
3730000	1.08964637462919
3735000	1.08964637462919
3740000	1.0896463746291896
3745000	1.08964637462919
3750000	1.08964637462919
3755000	1.0896463746291902
3760000	1.0896463746291898
3765000	1.0896463746291896
3770000	1.0896463746291898
3775000	1.0896463746291905
3780000	1.0896463746291902
3785000	1.08964637462919
3790000	1.0896463746291898
3795000	1.08964637462919
3800000	1.0896463746291902
3805000	1.08964637462919
3810000	1.0896463746291902
3815000	1.0896463746291902
3820000	1.08964637462919
3825000	1.0896463746291902
3830000	1.0896463746291896
3835000	1.08964637462919
3840000	1.08964637462919
3845000	1.08964637462919
3850000	1.08964637462919
3855000	1.0896463746291902
3860000	1.0896463746291902
3865000	1.0896463746291902
3870000	1.0896463746291896
3875000	1.08964637462919
3880000	1.0896463746291902
3885000	1.0896463746291902
3890000	1.08964637462919
3895000	1.0896463746291902
3900000	1.0896463746291896
3905000	1.08964637462919
3910000	1.0896463746291902
3915000	1.0896463746291907
3920000	1.0896463746291898
3925000	1.0896463746291898
3930000	1.0896463746291902
3935000	1.0896463746291898
3940000	1.0896463746291905
3945000	1.0896463746291898
3950000	1.0896463746291893
3955000	1.08964637462919
3960000	1.0896463746291902
3965000	1.0896463746291896
3970000	1.0896463746291907
3975000	1.0896463746291898
3980000	1.0896463746291896
3985000	1.0896463746291902
3990000	1.0896463746291905
3995000	1.0896463746291902
4000000	1.0896463746291905
4005000	1.0896463746291898
4010000	1.08964637462919
4015000	1.0896463746291907
4020000	1.089646374629189
4025000	1.0896463746291898
4030000	1.0896463746291902
4035000	1.0896463746291893
4040000	1.0896463746291893
4045000	1.0896463746291896
4050000	1.0896463746291898
4055000	1.08964637462919
4060000	1.08964637462919
4065000	1.0896463746291905
4070000	1.0896463746291902
4075000	1.0896463746291902
4080000	1.0896463746291902
4085000	1.08964637462919
4090000	1.0896463746291902
4095000	1.0896463746291898
4100000	1.08964637462919
4105000	1.0896463746291898
4110000	1.0896463746291893
4115000	1.0896463746291896
4120000	1.0896463746291898
4125000	1.0896463746291898
4130000	1.0896463746291896
4135000	1.0896463746291902
4140000	1.08964637462919
4145000	1.0896463746291898
4150000	1.08964637462919
4155000	1.0896463746291902
4160000	1.08964637462919
4165000	1.0896463746291898
4170000	1.0896463746291896
4175000	1.08964637462919
4180000	1.08964637462919
4185000	1.08964637462919
4190000	1.0896463746291898
4195000	1.0896463746291898
4200000	1.0896463746291902
4205000	1.0896463746291902
4210000	1.08964637462919
4215000	1.0896463746291902
4220000	1.0896463746291898
4225000	1.0896463746291898
4230000	1.0896463746291905
4235000	1.08964637462919
4240000	1.0896463746291902
4245000	1.08964637462919
4250000	1.0896463746291905
4255000	1.0896463746291898
4260000	1.08964637462919
4265000	1.0896463746291905
4270000	1.0896463746291896
4275000	1.0896463746291902
4280000	1.08964637462919
4285000	1.0896463746291902
4290000	1.0896463746291898
4295000	1.0896463746291905
4300000	1.0896463746291902
4305000	1.0896463746291902
4310000	1.08964637462919
4315000	1.08964637462919
4320000	1.0896463746291902
4325000	1.08964637462919
4330000	1.0896463746291902
4335000	1.0896463746291896
4340000	1.0896463746291902
4345000	1.0896463746291896
4350000	1.08964637462919
4355000	1.0896463746291898
4360000	1.0896463746291902
4365000	1.08964637462919
4370000	1.0896463746291898
4375000	1.0896463746291898
4380000	1.0896463746291893
4385000	1.08964637462919
4390000	1.0896463746291898
4395000	1.0896463746291898
4400000	1.0896463746291898
4405000	1.08964637462919
4410000	1.0896463746291902
4415000	1.0896463746291896
4420000	1.08964637462919
4425000	1.0896463746291893
4430000	1.0896463746291898
4435000	1.0896463746291893
4440000	1.0896463746291896
4445000	1.0896463746291898
4450000	1.0896463746291898
4455000	1.0896463746291898
4460000	1.08964637462919
4465000	1.0896463746291896
4470000	1.0896463746291896
4475000	1.0896463746291898
4480000	1.0896463746291898
4485000	1.0896463746291893
4490000	1.08964637462919
4495000	1.0896463746291902
4500000	1.0896463746291898
4505000	1.0896463746291898
4510000	1.08964637462919
4515000	1.0896463746291902
4520000	1.08964637462919
4525000	1.0896463746291898
4530000	1.0896463746291905
4535000	1.0896463746291898
4540000	1.08964637462919
4545000	1.0896463746291902
4550000	1.08964637462919
4555000	1.0896463746291898
4560000	1.0896463746291896
4565000	1.0896463746291902
4570000	1.0896463746291902
4575000	1.089646374629189
4580000	1.0896463746291898
4585000	1.08964637462919
4590000	1.0896463746291896
4595000	1.0896463746291896
4600000	1.0896463746291896
4605000	1.0896463746291898
4610000	1.08964637462919
4615000	1.0896463746291898
4620000	1.0896463746291902
4625000	1.0896463746291893
4630000	1.08964637462919
4635000	1.0896463746291902
4640000	1.0896463746291902
4645000	1.0896463746291896
4650000	1.0896463746291893
4655000	1.0896463746291898
4660000	1.08964637462919
4665000	1.0896463746291905
4670000	1.0896463746291898
4675000	1.08964637462919
4680000	1.0896463746291898
4685000	1.0896463746291896
4690000	1.0896463746291898
4695000	1.0896463746291898
4700000	1.0896463746291891
4705000	1.0896463746291898
4710000	1.08964637462919
4715000	1.0896463746291905
4720000	1.0896463746291902
4725000	1.0896463746291898
4730000	1.0896463746291902
4735000	1.0896463746291898
4740000	1.08964637462919
4745000	1.0896463746291898
4750000	1.0896463746291905
4755000	1.08964637462919
4760000	1.0896463746291902
4765000	1.0896463746291896
4770000	1.0896463746291902
4775000	1.08964637462919
4780000	1.08964637462919
4785000	1.0896463746291902
4790000	1.08964637462919
4795000	1.08964637462919
4800000	1.0896463746291893
4805000	1.0896463746291893
4810000	1.0896463746291902
4815000	1.08964637462919
4820000	1.0896463746291898
4825000	1.0896463746291898
4830000	1.0896463746291902
4835000	1.0896463746291896
4840000	1.0896463746291898
4845000	1.08964637462919
4850000	1.0896463746291896
4855000	1.0896463746291902
4860000	1.0896463746291896
4865000	1.0896463746291898
4870000	1.08964637462919
4875000	1.08964637462919
4880000	1.0896463746291902
4885000	1.08964637462919
4890000	1.0896463746291896
4895000	1.08964637462919
4900000	1.08964637462919
4905000	1.0896463746291898
4910000	1.0896463746291905
4915000	1.0896463746291902
4920000	1.0896463746291902
4925000	1.08964637462919
4930000	1.0896463746291898
4935000	1.08964637462919
4940000	1.08964637462919
4945000	1.0896463746291898
4950000	1.0896463746291898
4955000	1.0896463746291905
4960000	1.08964637462919
4965000	1.0896463746291902
4970000	1.0896463746291896
4975000	1.0896463746291902
4980000	1.08964637462919
4985000	1.0896463746291902
4990000	1.08964637462919
4995000	1.0896463746291907

**Comment by walterxie** [comment]
There was parsing err. Not sure why you log space as delimiter, but Tracer only takes tab (\t). After I replaced all into tab, it was loaded very fast.

**Comment by rbouckaert** [comment]
Tracer starts fast, but does not show any trace, at least on my computer. Also, it is completely unresponsive, so cannot be used for anything else. I can show you next week. Can you see the trace?

**Comment by rbouckaert** [comment]
Same behaviour on Linux as on OS X, even when using only the first 50 entries.

**Comment by walterxie** [comment]
Are you sure the delimiter is tab? I just manually replaced the delimiter in your previous log, and it worked. The tracer version is 1.7.3. The log file and screenshot is attached.

<img width="1312" alt="Screenshot 2024-02-12 at 3 50 53 PM" src="https://github.com/beast-dev/tracer/assets/5743014/d02a54cd-d073-4f23-bbbf-3a19fa0ec15b">

[low-variance.txt](https://github.com/beast-dev/tracer/files/14234933/low-variance.txt)

**Comment by rbouckaert** [comment]
Thanks Walter -- the tabs are not the issue, but I use v1.7.2, which is currently the latest release on github. 
Where can I get v1.7.3?

**Comment by rbouckaert** [comment]
Got it from the pre-release and problem is fixed in v1.7.3.

**Comment by rbouckaert** [comment]
Hmm, still seems to be an issue, even with v1.7.3: [x.log](https://github.com/beast-dev/tracer/files/14349941/x.log)

**Comment by rambaut** [comment]
Looks like it is in an infinite loop in the KDE estimator. Needs a max number of iterations or some check for variance before attempting the KDE.

**Comment by rambaut** [comment]
The variation is in the 15th decimal place and then only takes 3 values suggesting rounding error. 
Probably the best option is to just flag traces with a range less than some small number, towards the limit of double precision, as constant (if this is real variation of interest, this variable should probably be in log space).

**Comment by rambaut** [comment]
Changed TraceDistribution check for constant value to:
 ` isConstant = MachineAccuracy.isSame(maximum, minimum);`
