### ISSUE TITLE
Change state numbers to longs

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#23]
ESSs (for example) overflow if > 2B states

**Comment by walterxie** [comment]
change all burnIn and stepSize to long

![screen shot 2017-03-09 at 2 32 49 pm](https://cloud.githubusercontent.com/assets/5743014/23732043/b026b15a-04d5-11e7-90da-7fcf9ac61912.png)
![screen shot 2017-03-09 at 2 32 49 pm](https://cloud.githubusercontent.com/assets/5743014/23732044/b1c45a76-04d5-11e7-9058-de0b1a6fcd14.png)
