### ISSUE TITLE
Move Tracer to here

### ISSUE THREAD

**Issue by walterxie** [beast-dev/tracer#24]
@alexeid  @rambaut @msuchard 
Are you happy to use this repository as the future "home" of Tracer?

Cheers,
Walter

**Comment by walterxie** [comment]
@alexeid @rambaut @msuchard
This is more complex than I thought. At my first attempt to separate Tracer, I considered it depended on BEAST 1 project, as the models used in Tracer's analysis (as well as some distributions, basic GUI components, etc.) were mostly developed inside the BEAST 1. However, I found multiple reasons shortly that BEAST 1 had to use Tracer's functions, such as the post-analysis XML.

I think the only way to do this is to make Tracer XML free and totally independent to BEAST 1, and then import Tracer library in BEAST 1. 

Cheers,
Walter

**Comment by rambaut** [comment]
I think everything in dr.app.tracer can go into the Tracer repo and then build on a beast.jar. Tracer is essentially a GUI app. There should be no dependencies on dr.app.tracer in the beast code base (and if there are we can sort them).

**Comment by rambaut** [comment]
OK there is a compiling and running version of Tracer on this repo. The ant file will build platform specific versions. The beast.jar library currently is just the whole thing but it would be easy to create a pared down jar for this purpose in the beast ant script.
