### ISSUE TITLE
remove generic to use TraceType only? 

### ISSUE THREAD

**Issue by walterxie** [beast-dev/tracer#29]
@rambaut 
Dear Andrew,

Do you think we really need generic? It looks 2 data types (Double and String) are enough for all calculations, according to the code below. Integer is not necessary, furthermore, all terrible generic classes and functions can be removed. TraceType can be used to distinguish 3 trace types we designed.

private Trace createTrace(String name, TraceType traceType) {
        if (traceType.isNumber()) {
            return new Trace<Double>(name, traceType);
        } else {
            return new Trace<String>(name, TraceType.CATEGORICAL);
        }
    }

**Comment by rambaut** [comment]
We don't need a generic. I suggest having only List<Double> as the internal storage. For categorical (non-numerical) traces, we could store integers (in the Double array) and an array of strings for the category labels.
