### ISSUE TITLE
Scales on density plots gone bad

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#32]
Version 1.6
<img width="724" alt="v1 6" src="https://cloud.githubusercontent.com/assets/686405/23832366/5a22e97a-072a-11e7-94e0-6d1a3c7325ec.png">

Current trunk:
<img width="802" alt="trunk" src="https://cloud.githubusercontent.com/assets/686405/23832361/2d793db6-072a-11e7-816b-613e8390ccda.png">

**Comment by walterxie** [comment]
The below code should be outside of "if (plot != null)", otherwise "densityChart.addPlot(plot2)" will be affected by other traces.

if (trace.getTraceType().isDiscrete()) {
...
} else {
    densityChart.setXAxis(new LinearAxis());
}
