### ISSUE TITLE
Conditional probability dialog has confusing text

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#33]
<img width="354" alt="cond" src="https://cloud.githubusercontent.com/assets/686405/23832393/e772d29a-072a-11e7-8f07-48fe00cca6fa.png">

`Lower to rescale value` ? It isn't really rescaling.

**Comment by walterxie** [comment]
![screen shot 2017-03-16 at 4 59 40 pm](https://cloud.githubusercontent.com/assets/5743014/23981262/00669498-0a6a-11e7-9b9b-22b58dfc2c07.png)
