### ISSUE TITLE
Condition a continuous parameter on the values in a categorical

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#34]
Filter values for when (say) an indicator is 1.

**Comment by walterxie** [comment]
@rambaut 
I think this feature exists. You can set lower=1 and upper=1.

![screen shot 2017-04-20 at 9 36 28 am](https://cloud.githubusercontent.com/assets/5743014/25203343/fa5266aa-25ac-11e7-8037-7b1fe4fd274c.png)

**Comment by rambaut** [comment]
That’s an integer. Categorical’s don’t have an order.

A.

**Comment by walterxie** [comment]
If categorical, then the combobox is applied:

![screen shot 2017-04-20 at 9 42 37 am](https://cloud.githubusercontent.com/assets/5743014/25203578/d2af063e-25ad-11e7-8533-26527b4fc396.png)
