### ISSUE TITLE
Traces with the same name in the same trace file

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#35]
The first one with the name is shown. Need to add a suffix number to the trace name on loading.

**Comment by walterxie** [comment]
@rambaut Can you give more details? I do not think we should allow the same name given to different parameters logged in the same log file.

**Comment by rambaut** [comment]
I don't think we should disallow it. Just append a number.

**Comment by walterxie** [comment]
Because this equals to allow the same names for different variables in one function. I cannot think of any motivation to implement this. If a BEAST log duplicates parameters, then we should fix the logging bug, instead to let it pass to post-analysis.

**Comment by rambaut** [comment]
My philosophy with software is to not annoy the user. If they want to load a file with identical column headings, then let them. By putting this in the issue list, I wasn't suggesting you need to implement it.

**Comment by mtolkoff** [comment]
It's not always a logging bug. For example if you name your parameters
"parameter1" ... "parameter15" and each of these parameters is of length
15, then it's ambiguous whether "parameter115" is the 5th element of
parameter 11 or the 15th element of parameter1. You can solve this by
changing the parameter scheme to be "parameter11.5" for example, but that
precludes the user for including another parameter named "parameter11.5"
elsewhere in the XML.

**Comment by rambaut** [comment]
It is currently a bug as it neither deals with the issue (by appending numbers) or disallows identical trace names. It also has unexpected and erroneous behaviour.
