### ISSUE TITLE
Statistics for ordinal or categorical traces with only one state are not displayed

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#44]
ACT and ESS for ordinal traces with only one state are not shown in the Statistics table (on mac an odd question mark character appears).

**Comment by walterxie** [comment]
@rambaut 

I prefer to disallow the inadequate sample size in log file. Please see issue : Inadequate sample size in log file causes burnin < stepsize #43. But it seems #43 did not block the log having less than 3 rows.

**Comment by rambaut** [comment]
By 'state' I mean one value. I.e., all "1".

**Comment by walterxie** [comment]
@rambaut 

If only one unique value, such as all "1", then ACT = 0. But should ESS = 1 or INF?
