### ISSUE TITLE
Joint-density plot of 2 ordinal traces

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#49]
Need to think about how to do this. Also an ordinal vs continuous or other combinations.

**Comment by rambaut** [comment]
For ordinal or categorical vs a real trace, always put the categorical on the X axis and show HPD bounds (or box-wisker?) for the continuous.

**Comment by msuchard** [comment]
Maybe a frequency table?

**Comment by maxbiostat** [comment]
If you want to be fancy you can just make a heat table from the frequency table. That would of course involve coding all that up plus sticking a scale strip somewhere in the plot...

**Comment by walterxie** [comment]
@msuchard @rambaut  

I have implemented the two-way frequency table for categorical values, including joint prob, conditional prob, and counts. It could be easy to extend to ordinal, but no idea how to mix these two types with real numbers.

**Comment by walterxie** [comment]
Just get an idea, we could use DiscreteJChart for all values, but define bins for real numbers, it therefore can be used to a two-way frequency table.

**Comment by walterxie** [comment]
@rambaut @rambaut @msuchard 
TangHuLuPlot:

Create a string of bubbles to visualise the joint probability between two ordinal random variables.
The size of circle is proportional to the joint probability, the blue coloured circle is in the credible set of given a probability threshold default to 0.95, the red is in the incredible set.
 
TangHuLu is a traditional Chinese snack of candied fruit normally sugar-coated hawthorns on a stick.

![screen shot 2017-03-30 at 12 14 46 pm](https://cloud.githubusercontent.com/assets/5743014/24482510/3f92ba86-154e-11e7-8de1-ad78eee87589.png)

![screen shot 2017-03-30 at 12 15 23 pm](https://cloud.githubusercontent.com/assets/5743014/24482517/475e7be2-154e-11e7-9b75-be6175614484.png)

![screen shot 2017-03-30 at 12 15 55 pm](https://cloud.githubusercontent.com/assets/5743014/24482522/4f534e40-154e-11e7-912e-13c08090ef26.png)
