### ISSUE TITLE
Joint-marginal of two ordinal or categorical traces doesn't display

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#5]
_From @rambaut on July 22, 2016 9:59_

Could use a 'circle plot' with circles areas proportional to joint probability.

_Copied from original issue: beast-dev/beast-mcmc#826_

**Comment by walterxie** [comment]
duplicated to #49

**Comment by walterxie** [comment]
Create TangHuLuPlot to solve "Joint-density plot of 2 ordinal traces" #49

**Comment by walterxie** [comment]
Joint-density plot of 1 ordinal and 1 categorical traces #60

**Comment by walterxie** [comment]
add box plot #61 for discrete vs continuous. I think all done.
