### ISSUE TITLE
Copied data from ordinal density plot is continuous

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#7]
_From @rambaut on July 22, 2016 8:20_

_Copied from original issue: beast-dev/beast-mcmc#824_

**Comment by walterxie** [comment]
@rambaut 
Any detail or screen shot?

**Comment by walterxie** [comment]
"Export data" from either an integer or categorical trace in marginal-prob-distribution panel does not export the correct value of that trace. They looked like points calculated for plotting.
[t.txt](https://github.com/beast-dev/tracer/files/1164440/t.txt)

**Comment by walterxie** [comment]
@rambaut 
It seems fixed somehow:

batRABV.log.txt	host.indicators1	host.indicators2	host.indicators3
0.0	0.9908333333333333	0.9930555555555556	0.9897222222222222
1.0	0.009166666666666667	0.006944444444444444	0.010277777777777778
