### ISSUE TITLE
Very short log BEAST runs in Tracer

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/tracer#71]
The latest code for Tracer no longer allows for very short runs to be visually inspected for signs of mixing and shows the following error message: 'Problem with trace file: Inadequate sample size (X) causes burn in XXXX < step size XXXXX !'.

While I do understand the reason behind this decision, would it be possible to still show the traces (which is not the case right now) and disable the upper panel on the right (i.e. the one with the summary statistics) or print the error message there?

**Comment by rambaut** [comment]
I agree. There is no point in having restrictions on what people can do with Tracer. If the burnin < stepsize just treat the burnin as zero.

A.

**Comment by msuchard** [comment]
I also agree.    @walterxie -- please revert.

**Comment by walterxie** [comment]
Refer to Inadequate sample size in log file causes burnin < stepsize #43
