### ISSUE TITLE
Fresh install on macOS 10.12 generates (work-around-able) error ...

### ISSUE THREAD

**Issue by msuchard** [beast-dev/tracer#80]
`To open "Tracer c1.6.0" you need to install the legacy Java SE 6 runtime.`. We may or may not care.

**Comment by rambaut** [comment]
You can also install Java 8 JDK and it will work but there is no JVM in Mac OS by default. I intended to look into packaging the JVM in the app bundle which I think you can do.

**Comment by GuyBaele** [comment]
I have Java 8 JDK but still get that legacy message.

**Comment by rambaut** [comment]
I thought I had upgraded the startup script in the OSX package to fix this. Will try to find a clean machine for testing.
