### ISSUE TITLE
Create a Mac OS .dmg with a drag to Applications layout

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#86]
Standard for Mac OS X dmg installs. Can this be done in ANT build script?

**Comment by walterxie** [comment]
@rambaut 
Hi, Andrew,
 
We have ANT for this in BEAST 2 build.xml <target name="mac"> https://github.com/CompEvol/beast2/blob/master/build.xml
![screen shot 2017-07-31 at 10 13 40 am](https://user-images.githubusercontent.com/5743014/28757516-f8b78a92-75d8-11e7-864a-8fcf144da7f6.png)

In addition, <property name="AppleSigner" value="Developer ID Application: ... /> can make your program as a "signed" application in Mac, which would not warning you when opening it. I recommend you to apply it for BEAST 1 and Tracer. 

Cheers,
Walter
