### ISSUE TITLE
Using the 'reload' button clears settings.

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#89]
Trace settings such as type (real, integer etc) are reset when the reload button is clicked.

**Comment by GuyBaele** [comment]
When you say 'clears settings', do you mean that a dash appears in the Type column? Do you have an example .log file that contains a mixture of the different types?

**Comment by rambaut** [comment]
Clears the axis/chart settings, the legend and colour by options.

**Comment by GuyBaele** [comment]
Think my commit from last night took care of this. If not, please post the steps to reproduce a specific problem.
