### ISSUE TITLE
If trace files have different types for a trace, combined trace permanently disappears.

### ISSUE THREAD

**Issue by rambaut** [beast-dev/tracer#92]
Load 2 trace files. Select one of them and set a trace to integer (the other one remains as 'real'). The combined trace disappears (which is fine - although perhaps it should be greyed out?). When you set the first trace file back to real (so they are both the same), the combined log doesn't come back.

**Comment by GuyBaele** [comment]
Combined trace disappears when setting a trace to a different type, but combined log now also comes back when the change has been undone.
